Patch MyDatabase table creation
Update the MyDatabase class such that:

* create_table and insert_data are patched to accept a posix_path arg instead of a file that can be opened --- I was getting the following exception prior to this commit:

TypeError: coercing to Unicode: need string or buffer, PosixPath found

This seems to simplify the code and allows it to work on a unix based OS. Can you pull this down to see if it works for you?